# Generated by Django 5.0.1 on 2025-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_text_task_title_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='break_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='task',
            name='pomodoro_duration',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='task',
            name='pomodoros_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
