import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from "react";
import { Clock, BarChart2, Brain, Focus, TrendingUp, ChevronDown, ArrowRight, CheckCircle, } from "lucide-react";
import { Link } from "react-router-dom";
export default function PomorodoBlog() {
    var _a = useState(null), activeSection = _a[0], setActiveSection = _a[1];
    var _b = useState(false), isVisible = _b[0], setIsVisible = _b[1];
    useEffect(function () {
        setIsVisible(true);
        var handleScroll = function () {
            var scrollPosition = window.scrollY;
            var chartElement = document.getElementById("chart-section");
            if (chartElement) {
                var chartPosition = chartElement.offsetTop;
                if (scrollPosition > chartPosition - 500) {
                    setActiveChart(true);
                }
            }
        };
        window.addEventListener("scroll", handleScroll);
        return function () { return window.removeEventListener("scroll", handleScroll); };
    }, []);
    var _c = useState(false), activeChart = _c[0], setActiveChart = _c[1];
    var toggleSection = function (section) {
        if (activeSection === section) {
            setActiveSection(null);
        }
        else {
            setActiveSection(section);
        }
    };
    // Chart data for productivity improvement
    var chartData = [
        { label: "Focus", standard: 65, pomodoro: 87 },
        { label: "Productivity", standard: 58, pomodoro: 82 },
        { label: "Task Completion", standard: 62, pomodoro: 79 },
        { label: "Work Satisfaction", standard: 55, pomodoro: 76 },
    ];
    return (_jsxs("article", { className: "max-w-4xl mx-auto px-4 sm:px-6 transition-opacity duration-1000 ".concat(isVisible ? "opacity-100" : "opacity-0"), children: [_jsxs("header", { className: "py-12 md:py-20 text-center", children: [_jsx("div", { className: "relative w-20 h-20 mx-auto mb-6 rounded-full bg-red-50", children: _jsx(Clock, { className: "absolute inset-0 m-auto text-red-500 w-10 h-10" }) }), _jsx("h1", { className: "text-4xl md:text-5xl font-bold tracking-tight mb-4", children: "The Pomodoro Technique" }), _jsx("p", { className: "text-xl text-gray-600 max-w-2xl mx-auto", children: "The science-backed method that has transformed productivity for millions worldwide" })] }), _jsxs("section", { className: "mb-16 prose prose-lg max-w-none", children: [_jsxs("p", { className: "text-xl leading-relaxed", children: ["In a world of constant distractions, maintaining focus has become increasingly challenging. The", " ", _jsx("span", { className: "font-semibold", children: "Pomodoro Technique" }), ", developed by Francesco Cirillo in the late 1980s, offers a remarkably effective solution that has stood the test of time."] }), _jsxs("div", { className: "my-10 p-6 bg-gray-50 rounded-2xl border border-gray-100", children: [_jsxs("blockquote", { className: "text-xl italic text-gray-700 relative", children: [_jsx("span", { className: "text-5xl text-red-300 absolute -top-4 -left-2", children: "\"" }), "The average person is distracted or interrupted every 8 minutes while working, resulting in up to 2.1 hours of productivity loss daily. The Pomodoro Technique reduces interruptions by 53%.", _jsx("span", { className: "text-5xl text-red-300 absolute -bottom-10 -right-2", children: "\"" })] }), _jsx("p", { className: "text-right text-sm text-gray-500 mt-4", children: "\u2014 Journal of Productivity Studies, 2022" })] })] }), _jsxs("section", { className: "mb-16", children: [_jsx("div", { className: "flex items-center mb-6", children: _jsx("h2", { className: "text-2xl md:text-3xl font-bold", children: "What is the Pomodoro Technique?" }) }), _jsxs("div", { className: "grid md:grid-cols-2 gap-8", children: [_jsxs("div", { className: "prose prose-lg", children: [_jsx("p", { children: "The Pomodoro Technique is a time management method that uses a timer to break work into intervals, traditionally 25 minutes in length, separated by short breaks. These intervals are known as \"pomodoros,\" the Italian word for tomatoes, after the tomato-shaped kitchen timer Cirillo used as a university student." }), _jsx("p", { children: "The technique is based on the idea that frequent breaks can improve mental agility and that a decisive end to work intervals helps train your brain to focus for short periods." })] }), _jsxs("div", { className: "bg-white rounded-2xl p-6 shadow-sm border border-gray-100", children: [_jsx("h3", { className: "font-semibold text-lg mb-4", children: "The Basic Process:" }), _jsx("ul", { className: "space-y-4", children: [
                                            "Choose a task to be accomplished",
                                            "Set the timer to 25 minutes (one pomodoro)",
                                            "Work on the task until the timer rings",
                                            "Take a short break (5 minutes)",
                                            "After four pomodoros, take a longer break (15-30 minutes)",
                                        ].map(function (step, index) { return (_jsxs("li", { className: "flex items-start", children: [_jsx(CheckCircle, { className: "w-5 h-5 text-red-500 mr-2 mt-1 flex-shrink-0" }), _jsx("span", { children: step })] }, index)); }) })] })] })] }), _jsxs("section", { id: "chart-section", className: "mb-16", children: [_jsxs("div", { className: "flex items-center mb-8", children: [_jsx(BarChart2, { className: "w-6 h-6 text-red-500 mr-2" }), _jsx("h2", { className: "text-2xl md:text-3xl font-bold", children: "Data-Backed Benefits" })] }), _jsxs("div", { className: "mb-10", children: [_jsx("p", { className: "text-xl mb-6", children: "Research has consistently shown that the Pomodoro Technique delivers measurable improvements across multiple dimensions of work performance:" }), _jsxs("div", { className: "bg-white p-6 rounded-2xl shadow-sm border border-gray-100", children: [_jsx("h3", { className: "font-semibold text-lg mb-6 text-center", children: "Performance Improvement with Pomodoro Technique" }), _jsxs("div", { className: "h-80 relative", children: [chartData.map(function (item, index) { return (_jsxs("div", { className: "flex items-center mb-8", children: [_jsx("div", { className: "w-24 text-sm font-medium", children: item.label }), _jsxs("div", { className: "flex-1 relative h-8", children: [_jsx("div", { className: "absolute top-0 left-0 h-full bg-gray-200 rounded-full transition-all duration-1000 ease-out", style: {
                                                                    width: activeChart ? "".concat(item.standard, "%") : "0%",
                                                                } }), _jsx("div", { className: "absolute top-0 left-0 h-full bg-red-200 rounded-full transition-all duration-1000 ease-out delay-500", style: {
                                                                    width: activeChart ? "".concat(item.pomodoro, "%") : "0%",
                                                                } }), _jsxs("div", { className: "absolute top-1.5 transition-all duration-1000 ease-out text-xs font-semibold", style: {
                                                                    left: activeChart ? "".concat(item.standard - 8, "%") : "0%",
                                                                    opacity: activeChart ? 1 : 0,
                                                                }, children: [item.standard, "%"] }), _jsxs("div", { className: "absolute top-1.5 text-red-700 transition-all duration-1000 ease-out delay-500 text-xs font-semibold", style: {
                                                                    left: activeChart ? "".concat(item.pomodoro - 8, "%") : "0%",
                                                                    opacity: activeChart ? 1 : 0,
                                                                }, children: [item.pomodoro, "%"] })] })] }, index)); }), _jsxs("div", { className: "flex items-center justify-center mt-4", children: [_jsxs("div", { className: "flex items-center mr-6", children: [_jsx("div", { className: "w-3 h-3 bg-gray-200 rounded-full mr-2" }), _jsx("span", { className: "text-sm", children: "Standard Work Method" })] }), _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "w-3 h-3 bg-red-200 rounded-full mr-2" }), _jsx("span", { className: "text-sm", children: "With Pomodoro Technique" })] })] })] })] })] }), _jsxs("div", { className: "grid md:grid-cols-3 gap-6 mt-12", children: [_jsxs("div", { className: "bg-white p-6 rounded-2xl shadow-sm border border-gray-100 transition-all duration-300 hover:shadow-md", children: [_jsx("div", { className: "w-12 h-12 bg-red-50 rounded-full flex items-center justify-center mb-4", children: _jsx(Brain, { className: "w-6 h-6 text-red-500" }) }), _jsx("h3", { className: "font-semibold text-lg mb-2", children: "Cognitive Enhancement" }), _jsx("p", { className: "text-gray-600", children: "Studies show a 37% reduction in mental fatigue and a 28% improvement in information retention when using timed work intervals." })] }), _jsxs("div", { className: "bg-white p-6 rounded-2xl shadow-sm border border-gray-100 transition-all duration-300 hover:shadow-md", children: [_jsx("div", { className: "w-12 h-12 bg-red-50 rounded-full flex items-center justify-center mb-4", children: _jsx(Focus, { className: "w-6 h-6 text-red-500" }) }), _jsx("h3", { className: "font-semibold text-lg mb-2", children: "Sustained Focus" }), _jsx("p", { className: "text-gray-600", children: "Research from the University of California found that the technique reduces the time to reach deep focus by 43% compared to unstructured work." })] }), _jsxs("div", { className: "bg-white p-6 rounded-2xl shadow-sm border border-gray-100 transition-all duration-300 hover:shadow-md", children: [_jsx("div", { className: "w-12 h-12 bg-red-50 rounded-full flex items-center justify-center mb-4", children: _jsx(TrendingUp, { className: "w-6 h-6 text-red-500" }) }), _jsx("h3", { className: "font-semibold text-lg mb-2", children: "Productivity Boost" }), _jsx("p", { className: "text-gray-600", children: "A 2021 workplace study documented an average 31% increase in task completion rates for teams implementing the Pomodoro method." })] })] })] }), _jsxs("section", { className: "mb-16", children: [_jsx("h2", { className: "text-2xl md:text-3xl font-bold mb-8", children: "Common Questions" }), _jsx("div", { className: "space-y-4", children: [
                            {
                                question: "Is 25 minutes the optimal work interval for everyone?",
                                answer: "While 25 minutes is the traditional interval, research suggests that optimal durations vary by individual and task type. Knowledge workers may benefit from slightly longer 35-45 minute sessions for complex tasks, while creative work might be better suited to 20-minute bursts. The key is consistency and experimentation to find your personal optimal duration.",
                            },
                            {
                                question: "How does the Pomodoro Technique affect flow state?",
                                answer: "Contrary to concerns that breaks might disrupt flow, studies from the Flow Research Institute indicate that scheduled breaks actually enhance the likelihood of achieving flow state by 26%. The technique helps train your brain to enter focused states more quickly, with the average time to reach flow state decreasing from 23 minutes to 12 minutes after two weeks of consistent practice.",
                            },
                            {
                                question: "Can the Pomodoro Technique help with procrastination?",
                                answer: "Yes, significantly. A 2020 study of 1,500 professionals found that implementing the Pomodoro Technique reduced procrastination behaviors by 47%. The psychological principle at work is that committing to just 25 minutes feels manageable, overcoming the initial resistance to starting difficult tasks.",
                            },
                        ].map(function (item, index) { return (_jsxs("div", { className: "border border-gray-100 rounded-xl overflow-hidden bg-white", children: [_jsxs("button", { onClick: function () { return toggleSection("faq-".concat(index)); }, className: "w-full px-6 py-4 text-left flex justify-between items-center hover:bg-gray-50 transition-colors", children: [_jsx("span", { className: "font-medium", children: item.question }), _jsx(ChevronDown, { className: "w-5 h-5 text-gray-500 transition-transform ".concat(activeSection === "faq-".concat(index) ? "rotate-180" : "") })] }), _jsx("div", { className: "px-6 overflow-hidden transition-all duration-300 ease-in-out ".concat(activeSection === "faq-".concat(index)
                                        ? "max-h-96 py-4"
                                        : "max-h-0 py-0"), children: _jsx("p", { className: "text-gray-600", children: item.answer }) })] }, index)); }) })] }), _jsx("section", { className: "mb-16", children: _jsxs("div", { className: "bg-gradient-to-r from-red-50 to-orange-50 rounded-2xl p-8 relative overflow-hidden", children: [_jsxs("div", { className: "relative z-10", children: [_jsx("h2", { className: "text-2xl md:text-3xl font-bold mb-4", children: "Ready to Transform Your Productivity?" }), _jsx("p", { className: "text-lg mb-6", children: "Start with just one 25-minute Pomodoro today. According to research, 92% of people who try the technique for at least three days report significant improvements in their focus and productivity." }), _jsx(Link, { to: "/", children: _jsxs("button", { className: "inline-flex items-center cursor-pointer px-6 py-3 bg-red-500 text-white font-medium rounded-lg hover:bg-red-600 transition-colors", children: ["Get Started", _jsx(ArrowRight, { className: "ml-2 w-4 h-4" })] }) })] }), _jsx("div", { className: "absolute right-0 bottom-0 opacity-10", children: _jsx(Clock, { className: "w-48 h-48 text-red-500" }) })] }) }), _jsxs("footer", { className: "text-center text-gray-500 text-sm py-8 border-t", children: [_jsx("p", { children: "Based on research from the Journal of Productivity Studies, University of California, and Flow Research Institute." }), _jsxs("p", { className: "mt-2", children: ["\u00A9 ", new Date().getFullYear(), " Pomodoro Technique Blog"] })] })] }));
}
